---
title: "animal-crossing"
author: "Orla"
date: "4/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())
critic <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/critic.tsv')
user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')
items <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/items.csv')
villagers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv')
```

```{r}

```

### Text Analysis

```{r}
critic %>%
  ggplot(aes(grade)) +
  geom_histogram()

user_reviews %>%
  ggplot(aes(grade)) +
  geom_histogram()

head(user_reviews$text)
```

```{r}
library(tidytext)
library(lubridate)

user_review_words <- user_reviews %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words, by = 'word') %>%
  count(user_name, date, grade, word)

user_review_words
```

```{r}
by_week <- user_reviews %>%
  group_by(week = floor_date(date, "week", week_start = 1)) %>%
  summarize(nb_reviews = n(),
            avg_grade = mean(grade),
            pct_zero = mean(grade == 0),
            pct_ten = mean(grade == 10))

by_week %>%
  ggplot(aes(week, avg_grade)) +
  geom_line() +
  geom_point(aes(size = nb_reviews)) +
  expand_limits(y = 0) +
  labs(x = "Time",
       y = "Average grade",
       size = "# of reviews")

user_reviews %>%
  ggplot(aes(grade)) +
  geom_histogram() +
  labs(title = "Most reviews were very low or very high")

by_week %>%
  gather(type, value, contains("pct")) %>%
  mutate(type = ifelse(type == "pct_zero", "% rated 0", "% rated 10")) %>%
  ggplot(aes(week, value, color = type)) +
  geom_line() +
  geom_point(aes(size = nb_reviews)) +
  scale_y_continuous(labels = scales::percent) +
  expand_limits(y = 0) +
  labs(x = "Time",
       y = "% of reviews",
       size = "Total reviews in week",
       title = "Reviews got more polarizing in middle of game")
```